#pragma kernel RadixHistogram

#define GROUP_SIZE 256

StructuredBuffer<int> g_KeyBuffer;
RWStructuredBuffer<int> g_HistogramBuffer;

int g_ItemCount;
int g_KeyShift;

[numthreads(GROUP_SIZE, 1, 1)]
void RadixHistogram(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= (uint) g_ItemCount)
        return;
    int key = g_KeyBuffer[id.x];
    int subKey = (key >> g_KeyShift) & 0xF;
    for (int i = 0; i < 16; i++)
    	g_HistogramBuffer[g_ItemCount * i + id.x] = i == subKey ? 1 : 0;
}